### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by woodyXwt** [megvii-research/DPGN#18]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from dataloader import MiniImagenet, TieredImagenet, Cifar, CUB200, DataLoader
  File "/data/amax/users/wuti/DPGN-master/dataloader.py", line 9, in <module>
    import torchvision.transforms as transforms
  File "/home/amax/anaconda3/envs/wuti_py35/lib/python3.5/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/amax/anaconda3/envs/wuti_py35/lib/python3.5/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/amax/anaconda3/envs/wuti_py35/lib/python3.5/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/amax/anaconda3/envs/wuti_py35/lib/python3.5/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/amax/anaconda3/envs/wuti_py35/lib/python3.5/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/amax/anaconda3/envs/wuti_py35/lib/python3.5/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by woodyXwt** [comment]
..

**Comment by woodyXwt** [comment]
.
